// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrwzuzfogcwxuunduqyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyd3p1emZvZ2N3eHV1bmR1cXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjA5MjgsImV4cCI6MjA3MTA5NjkyOH0.M6fe64Qh1MupZuWZICyVZhEFzzENCx1rtGgCoBBVX7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});